services:
  scrapi:
    build: ./scrapi
    container_name: scrapi
    environment:
      - EVAL_PROJ_SDK_KEY=${EVAL_PROJ_SDK_KEY}
      - BENCH_CLUSTER_SDK_KEY=${BENCH_CLUSTER_SDK_KEY}
    image: scrapi:latest
    ports:
      - "8000:8000"
    volumes:
      - ./shared-volume:/shared-volume

  docker-stats:
    build: ./docker-stats
    container_name: docker-stats
    image: docker-stats:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared-volume:/shared-volume

  # ------------------------------------------------------------------------ [ SDKs ]

  dotnet-core:
    build: ./dotnet
    container_name: dotnet-core
    image: dotnet:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=core
      
  dotnet-legacy:
    build: ./dotnet
    container_name: dotnet-legacy
    image: dotnet:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=legacy

  java-core:
    build: ./java
    container_name: java-core
    image: java:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=core
      
  java-legacy:
    build: ./java
    container_name: java-legacy
    image: java:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=legacy

  node-core:
    build: ./node
    container_name: node-core
    image: node:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=core

  node-legacy:
    build: ./node
    container_name: node-legacy
    image: node:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=legacy

  php-core:
    build: ./php
    container_name: php-core
    image: php:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=core
    
  
  php-legacy:
    build: ./php
    container_name: php-legacy
    image: php:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=legacy

  python-core:
    build: ./python
    container_name: python-core
    image: python:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=core
  
  python-legacy:
    build: ./python
    container_name: python-legacy
    image: python:latest
    volumes:
      - ./shared-volume:/shared-volume
    environment:
      - SDK_VARIANT=legacy