[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[workspace]
members = ["statsig-lib", "statsig-ffi", "statsig-napi", "statsig-grpc", "statsig-pyo3", "examples/rust", "exec"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "ISC"
version = "0.0.1"
