[package]
name = "perf-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
statsig-rust = { path = "../../../statsig-rust" }
tokio = "1.39.1"
mimalloc = "0.1.46"

[profile.release]
debug = true
