name: Build Statsig FFI - macOS and Windows
description: Builds Statsig FFI libraries for specified targets

inputs:
  target:
    description: 'Target triple (e.g., aarch64-apple-darwin)'
    required: true

runs:
  using: composite
  steps:
    - name: Echo Inputs
      shell: bash
      run: |
        echo "Target: ${{ inputs.target }}"

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2

    - name: Install Rust Targets
      shell: bash
      run: rustup target add ${{ inputs.target }}

    - name: Build
      shell: bash
      run: |
        cargo build -p statsig_ffi --target=${{ inputs.target }}
        cargo build -p statsig_ffi --target=${{ inputs.target }} --release