name: Build Statsig FFI - macOS and Windows
description: Builds Statsig FFI libraries for specified targets

inputs:
  target:
    description: 'Target triple (e.g., aarch64-apple-darwin)'
    required: true

  build_for_release:
    description: 'Build for release'
    required: false

  app_private_key:
    description: The private key to use to authenticate as an app installation
    required: true

runs:
  using: composite
  steps:
    - name: Echo Inputs
      shell: bash
      run: |
        echo "Target: ${{ inputs.target }}"

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2

    - name: Install Rust Targets
      shell: bash
      run: rustup target add ${{ inputs.target }}

    - name: Install CLI Dependencies
      shell: bash
      run: cd cli && npm install

    - name: Build Debug
      shell: bash
      run: |
        cargo build -p statsig_ffi --target=${{ inputs.target }}

    - name: Build Release
      if: ${{ inputs.build_for_release == 'true' }}
      shell: bash
      run: |
        cargo build -p statsig_ffi --target=${{ inputs.target }} --release

    - name: Report Size Changes
      if: ${{ inputs.build_for_release == 'true' }}
      shell: bash
      env:
        GH_APP_ID: '229901'
        GH_APP_INSTALLATION_ID: '36921303'
        GH_APP_PRIVATE_KEY: ${{ inputs.app_private_key }}
      run: ./run report-size ${{ inputs.target }}