[package]
name = "statsig-pyo3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sigstat_python_core"
crate-type = ["cdylib"]

[dependencies]
sigstat = { path = "../statsig-lib" }
pyo3 = { version = "0.23.1", features = ["abi3-py37"] }
pyo3-async-runtimes = { version = "0.23.0", features = ["attributes", "tokio", "tokio-runtime"] }
tokio = "1.41.0"
serde_json = { version = "1.0.125", features = ["float_roundtrip"] }
