[package]
name = "statsig-node"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
sigstat = { path = "../statsig-lib" }
async-trait = "0.1.81"
napi = { version = "3.0.0-alpha.24", features = [
    "async",
    "anyhow",
    "serde-json",
] }
napi-derive = { version = "3.0.0-alpha.22", default-features = false, features = [
    "type-def",
] }
serde_json = "1.0.121"

#[dependencies.napi]
#version = "2"
#default-features = false
## see https://nodejs.org/api/n-api.html#node-api-version-matrix
#features = ["napi3", "async"]
#
#[dependencies.napi-derive]
#version = "2"
#features = ["type-def"]

[build-dependencies]
napi-build = { version = "2.1.4" }
#napi-build = "2"
