[package]
name = "sigstat"
version = "0.0.1"
edition = "2021"
license = "ISC"
description = "Core Statsig SDK written in Rust. For usage in multi-user server environments."

[dependencies]
tokio = {version = "1.39.1", features = ["full"]}
serde_json = {version = "1.0.125", features = ["float_roundtrip"]}
serde = { version = "1.0.204", features = ["derive"] }
chrono = "0.4.38"
regex = "1.10.5"
sha2 = "0.10.8"
base64 = "0.22.1"
async-trait = "0.1.81"
reqwest = { version = "0.12.5", features = ["json"] }
openssl = {version = "0.10.66", features = ["vendored"], optional = true}
log = "0.4.22"
simple_logger = "5.0.0"
lazy_static = "1.5.0"

[features]
default = []
vendored_openssl = ["openssl"]