name: Statsig Node Api

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  release:
    types: [released, prereleased]

jobs:
  action-info:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Event JSON
        run: |
          echo "-- Loading JSON from $GITHUB_EVENT_PATH --"
          cat $GITHUB_EVENT_PATH

      - name: Print Env
        run: printenv

  build:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        config:
          # -- Linux --

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            extras: --use-napi-cross --rebuild-openssl
            always_build: true

          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            extras: --use-napi-cross --rebuild-openssl

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extras: --use-napi-cross --rebuild-openssl

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            extras: --use-cross-compile --rebuild-openssl

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            extras: --use-cross-compile --rebuild-openssl

          # -- Windows --

          - os: windows-latest
            target: x86_64-pc-windows-msvc

          - os: windows-latest
            target: aarch64-pc-windows-msvc
            always_build: true

          # - os: windows-latest
          #   target: i686-pc-windows-msvc
          #   node_arch: x86

          # -- MacOS --

          - os: macos-latest
            target: x86_64-apple-darwin

          - os: macos-latest
            target: aarch64-apple-darwin
            always_build: true
            include_js_files: true
            
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build Statsig Napi
        if: ${{ github.ref_name == 'main' || matrix.config.always_build || github.event_name == 'release' }}
        uses: ./.github/actions/build-napi
        with:
          target: ${{ matrix.config.target }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          extras: ${{ matrix.config.extras }}
          node_arch: ${{ matrix.config.node_arch }}
          include_js_files: ${{ matrix.config.include_js_files }}

      - name: Attach Binary to Reelase
        if: ${{ github.event_name == 'release' }}
        uses: ./.github/actions/upload-release-asset
        with:
          repositories: ${{ github.event.repository.name }}
          asset_name: statsig-napi-${{ matrix.config.target }}
          app_private_key: ${{ secrets.KONG_APP_KEY_V2 }}
          pattern: statsig-napi/dist/lib/sigstat-napi.*.node

      - name: Attach JsFiles to Release
        if: ${{ github.event_name == 'release' && matrix.config.include_js_files }}
        uses: ./.github/actions/upload-release-asset
        with:
          repositories: ${{ github.event.repository.name }}
          asset_name: statsig-napi-js-files
          app_private_key: ${{ secrets.KONG_APP_KEY_V2 }}
          pattern: statsig-napi/dist/**/*.{json,js,d.ts}

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs:
      - build
    steps:
      - name: Trigger NPM Publish
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              workflow_id: 'statsig-napi-publish.yml',
              inputs: {
                workflow_run_id: '${{ github.run_id }}',
                release_commit_sha: '${{ github.event.release.target_commitish }}',
              }
            })
