name: Uploads a Release Asset
description: Uploads a Release Asset

inputs:
  repo:
    description: The repository to upload the asset to
    required: true

  patterns:
    description: The patterns to upload
    required: true

  asset_name:
    description: The name of the asset to upload
    required: true

  app_private_key:
    description: The private key to use to authenticate as an app installation
    required: true

runs:
  using: composite
  steps:
    - name: Echo Inputs
      shell: bash
      run: |
        echo "Release Tag: ${{ inputs.release_tag }}"
        echo "Patterns: ${{ inputs.patterns }}"
        echo "Asset Name: ${{ inputs.asset_name }}"

    - name: Install NPM Dependencies
      shell: bash
      run: cd cli && npm install

    - name: Upload Release Asset
      shell: bash
      env:
        GH_APP_ID: '229901'
        GH_APP_INSTALLATION_ID: '36921303'
        GH_APP_PRIVATE_KEY: ${{ inputs.app_private_key }}
      run: |
        ./run zip-files "${{ inputs.patterns }}" --output "${{ inputs.asset_name }}.zip"
        ./run gh-attach-asset "${{ inputs.asset_name }}.zip" --repo ${{ inputs.repo }} 
