name: Uploads a Release Asset
description: Uploads a Release Asset

inputs:
  repositories:
    description: The repository to upload the asset to
    required: true

  pattern:
    description: The pattern used to find the files to upload
    required: true

  asset_name:
    description: The name of the asset to upload
    required: true

  app_private_key:
    description: The private key to use to authenticate as an app installation
    required: true

runs:
  using: composite
  steps:
    - name: Echo Inputs
      shell: bash
      run: |
        echo "Release Tag: ${{ inputs.release_tag }}"
        echo "Pattern: ${{ inputs.pattern }}"
        echo "Asset Name: ${{ inputs.asset_name }}"

    - name: Install NPM Dependencies
      shell: bash
      run: cd cli && pnpm install

    - name: Upload Release Asset
      shell: bash
      env:
        GH_APP_ID: '229901'
        GH_APP_INSTALLATION_ID: '36921303'
        GH_APP_PRIVATE_KEY: ${{ inputs.app_private_key }}
      run: |
        ./tore zip-files "${{ inputs.pattern }}" --output "${{ inputs.asset_name }}.zip"
        for repo in ${{ inputs.repositories }}; do
            echo "Attaching asset to repo: $repo"
            ./tore gh-attach-asset "${{ inputs.asset_name }}.zip" --repo "$repo"
        done
