name: Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ inputs.gh_token }}

      - name: Run Rust Format
        run: cargo fmt --all --check

      - name: Run clippy
        # Exclude statsig-node because it's still early in development
        # run: cargo clippy --workspace --exclude statsig-node --all-features -- -D warnings
        run: cargo clippy --workspace --all-features -- -D warnings
