name: Cut Release

on:
  workflow_dispatch:
    inputs:
      kind:
        required: true
        type: choice
        options:
        - beta
        - patch
        - minor
        - major

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: true

jobs:
  work:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Cut Release
        env:
          KONG_APP_PRIVATE_KEY: ${{ secrets.KONG_APP_KEY_V2 }}
        run: |
          cargo exec bump-version --${{ inputs.kind }}
          cargo exec create-gh-release --repo-name ${{ github.event.repository.name }}
          cargo exec push-php
          cargo exec create-gh-release --repo-name sigstat-php
