name: Cut Release

on:
  workflow_dispatch:
    inputs:
      kind:
        required: true
        type: choice
        options:
        - beta
        - patch
        - minor
        - major

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: true

jobs:
  work:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.KONG_APP_ID }}
          private-key: ${{ secrets.SERVER_CORE_KONG_APP_PRIVATE_KEY }}
          owner: statsig-io

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Cut Release
        env:
          OCTOCRAB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          cargo exec bump-version --${{ inputs.kind }}
          cargo exec create-gh-release --repo-name ${{ github.event.repository.name }}
