name: Kong (Task)

on:
  workflow_call:
    inputs:
      sdk:
        type: string
        description: The SDK to build
        required: true

env:
  REPO_PAT: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
  FORCE_COLOR: true
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.setup.outputs.hash }}
    steps:
      - name: Clone Kong Repo
        run: git clone https://oauth2:$REPO_PAT@github.com/statsig-io/kong.git .

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup SDK Bridge
        id: setup
        run: |
          npm ci
          npm run kong -- setup ${{ inputs.sdk }} -v
          npm run kong -- bridge_hash ${{ inputs.sdk }} -v

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ inputs.sdk }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ inputs.sdk }}-buildx-${{ github.sha }}
            ${{ inputs.sdk }}-buildx-

      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: bridges/${{ inputs.sdk }}-bridge
          push: false
          load: true
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
          tags: |
            statsig/sdk-bridge:${{ steps.setup.outputs.hash }}
            ${{ inputs.sdk }}-bridge

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move Docker Build Cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache

      - name: Output Docker Image to File
        run: docker save statsig/sdk-bridge:${{ steps.setup.outputs.hash }} -o statsig-${{ inputs.sdk }}-bridge.tar

      - name: Upload Docker Image to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: statsig-${{ inputs.sdk }}-bridge.tar
          path: statsig-${{ inputs.sdk }}-bridge.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        filter: [common, common-rulesets-based, server]

    steps:
      - name: Clone Kong Repo
        run: git clone https://oauth2:$REPO_PAT@github.com/statsig-io/kong.git .

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Download Docker Image from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: statsig-${{ inputs.sdk }}-bridge.tar

      - name: Load Docker Image
        run: |
          docker load -i statsig-${{ inputs.sdk }}-bridge.tar
          docker tag statsig/sdk-bridge:${{ needs.build.outputs.hash }} ${{ inputs.sdk }}-bridge

      - name: List Docker Images
        run: docker images

      - name: Load Scrapi Responses from Github Cache
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: /tmp/kong/cache
          key: scrapi-cache-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Test Bridge
        run: |
          npm ci
          npm run kong -- test ${{ inputs.sdk }} -r -f __tests__/${{ matrix.filter }}/