name: Kong

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

env:
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}
  test_client_key: ${{ secrets.KONG_CLIENT_SDK_KEY }}
  repo_pat: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
  FORCE_COLOR: true

jobs:
  KONG:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [core-rust, core-napi, core-python, core-php, core-java]

    steps:
      - name: Get KONG
        run: git clone https://oauth2:$repo_pat@github.com/statsig-io/kong.git .

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Setup SDK Bridge
        id: setup
        run: |
          npm run kong -- setup ${{ matrix.sdk }} -v
          npm run kong -- bridge_hash ${{ matrix.sdk }} -v

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ matrix.sdk }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ matrix.sdk }}-buildx-${{ github.sha }}
            ${{ matrix.sdk }}-buildx-

      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: bridges/${{ matrix.sdk }}-bridge
          push: false
          load: true
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
          tags: |
            statsig/sdk-bridge:${{ steps.setup.outputs.hash }}
            ${{ matrix.sdk }}-bridge

      - # Temp fix
          # https://github.com/docker/build-push-action/issues/252
          # https://github.com/moby/buildkit/issues/1896
          name: Move Docker Build Cache
          run: |
            rm -rf ${{ runner.temp }}/.buildx-cache
            mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache

      - name: Run Tests [Non Rulesets]
        run: npm run kong -- test ${{ matrix.sdk }} -r -x /rulesets.test

      - name: Run Tests [Rulesets Only]
        run: npm run kong -- test ${{ matrix.sdk }} -r -f /rulesets.test
