name: Lint

on:
  push:
    branches: ['main']
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  # ------------------------------------------------------------ [ Clippy ]
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run clippy
        run: cargo clippy --workspace --all-features -- -D warnings

  # ------------------------------------------------------------ [ Rust Format ]
  rust-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Rust Format
        run: cargo fmt --all --check

  # ------------------------------------------------------------ [ Pyo3 Stub Gen ]
  pyo3-stub-gen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Run pyo3 stub gen
        run: |
          cargo run --bin stub_gen --package statsig-pyo3
          if [[ $(git status --porcelain) ]]; then
            echo "------------------------------"
            echo "Python stub gen has changes!"
            echo "Please run './tore build python' locally and commit the changes."
            echo "------------------------------"
            exit 1
          fi
