name: Release Bot

on:
  pull_request:
    types: [opened, reopened, closed]
    branches: [main, stable]
  release:
    types: [released, prereleased]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{ github.event_name }}"
          echo $GITHUB_CONTEXT || true
          echo $GITHUB_CONTEXT > github_context.json

      - name: Print GitHub Event JSON
        run: |
          echo "-- Loading JSON from $GITHUB_EVENT_PATH --"
          cat $GITHUB_EVENT_PATH

      - name: Print Env
        run: printenv

  sync-version:
    if: contains(github.head_ref, 'betas/') || contains(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Sync Version
        run: |
          pnpm install --dir cli
          ./run sync-version --commit-and-push

  run-publish-action:
    if: contains(github.ref, 'heads/releases')
    runs-on: ubuntu-latest
    steps:
      - uses: statsig-io/statsig-publish-sdk-action@main
        with:
          kong-private-key: ${{ secrets.KONG_GH_APP_PRIVATE_KEY }}
