name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: true

jobs:
  work:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.KONG_APP_ID }}
          private-key: ${{ secrets.SERVER_CORE_KONG_APP_PRIVATE_KEY }}
          owner: statsig-io

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Create Beta Tag
        env:
          OCTOCRAB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          cargo exec beta-tag-package
          cargo exec create-gh-release --commit-sha ${{ github.sha }} --repo-name ${{ github.repository }}
          cargo exec attach-gh-assets --asset-path README.md --repo-name ${{ github.repository }}
