name: Scheduled SDK Benchmark

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  
env:
  PERF_SDK_KEY: ${{ secrets.PERF_SDK_KEY }}
  CAPTURE: python $GITHUB_WORKSPACE/.github/benchmark_capture.py

jobs:
  bench-cluster:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      EVAL_PROJ_SDK_KEY: ${{ secrets.EVAL_PROJ_SDK_KEY }}
      BENCH_CLUSTER_SDK_KEY: ${{ secrets.BENCH_CLUSTER_SDK_KEY }}
    strategy:
      matrix:
        sdk-service:
          - dotnet-core
          - dotnet-legacy
          - java-core
          - java-legacy
          - node-core
          - node-legacy
          - php-core
          - php-legacy
          - python-core
          - python-legacy
          - rust-core
          - rust-legacy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bench Cluster
        run: |
          cd benchmarking/bench-cluster
          docker compose up --build scrapi docker-stats ${{ matrix.sdk-service }}

  ruby-bench:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Run Ruby Bench
        working-directory: examples/ruby/perf-bench
        run: |
          pip install psutil numpy
          
          bundle update
          eval ${{ env.CAPTURE }} bundle exec ruby ruby-legacy-bench.rb
        # eval ${{ env.CAPTURE }} bundle exec ruby ruby-core-bench.rb

