name: Scheduled SDK Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  
env:
  PERF_SDK_KEY: ${{ secrets.PERF_SDK_KEY }}
  CAPTURE: python $GITHUB_WORKSPACE/.github/benchmark_capture.py

jobs:
  node-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Node Core Bench
        working-directory: examples/node/perf-bench
        run: |
          pip install psutil numpy
          
          npm install
          eval ${{ env.CAPTURE }} npm run bench:core
          eval ${{ env.CAPTURE }} npm run bench:legacy

  python-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Bench
        working-directory: examples/python/perf-bench
        run: |
          pip install psutil -r requirements.txt
          eval ${{ env.CAPTURE }} python python-core-bench.py
          eval ${{ env.CAPTURE }} python python-legacy-bench.py

  java-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Java Bench
        working-directory: examples/java/perf-bench
        run: |
          pip install psutil numpy
          eval ${{ env.CAPTURE }} ./gradlew run_core -Prelease
          eval ${{ env.CAPTURE }} ./gradlew run_legacy -Prelease

  php-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: ffi
          ini-values: ffi.enable=1

      - name: Run PHP Bench
        working-directory: examples/php/perf-bench
        # We remove the opposite SDK to avoid namespace conflicts
        run: |
          pip install psutil numpy
          
          composer update
          rm -rf vendor/statsig/statsigsdk
          eval ${{ env.CAPTURE }} php src/PhpCoreBench.php

          composer update
          rm -rf vendor/statsig/statsig-php-core
          eval ${{ env.CAPTURE }} php src/PhpLegacyBench.php

  rust-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Run Rust Bench
        working-directory: examples/rust/perf-bench
        run: |
          pip install psutil numpy
          
          eval ${{ env.CAPTURE }} cargo run --release --bin core_bench
          eval ${{ env.CAPTURE }} cargo run --release --bin legacy_bench

  ruby-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Run Ruby Bench
        working-directory: examples/ruby/perf-bench
        run: |
          pip install psutil numpy
          
          bundle update
          eval ${{ env.CAPTURE }} bundle exec ruby ruby-legacy-bench.rb
        # eval ${{ env.CAPTURE }} bundle exec ruby ruby-core-bench.rb

