name: Scheduled SDK Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

env:
  PERF_SDK_KEY: ${{ secrets.PERF_SDK_KEY }}

jobs:
  node-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Node Core Bench
        working-directory: examples/node/perf-bench
        run: |
          npm install
          npm run bench

  python-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Bench
        working-directory: examples/python/perf-bench
        run: |
          pip install -r requirements.txt
          python python-core-bench.py
          python python-legacy-bench.py
