name: Statsig Rust Publish

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'The StatsigFFI workflow run that built the artifacts to publish'
        required: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4

      - name: Get Workflow Run Info
        id: workflow_run_info
        uses: ./.github/actions/verify-workflow-run-successful
        with:
          workflow_run_id: ${{ github.event.inputs.workflow_run_id }}

      - name: Checkout specific commit
        run: |
          git fetch
          git checkout ${{ steps.workflow_run_info.outputs.commit_sha }}

      - name: Cache Cargo Build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Apply Beta Tag
        run: cargo exec beta-tag-package

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Check and Publish Statsig Grpc Package
        run: |
          cargo package --allow-dirty --package sigstat-grpc
          cargo publish --allow-dirty --package sigstat-grpc

      - name: Check and Publish Statsig Lib Package
        run: |
          cargo package --allow-dirty --package sigstat
          cargo publish --allow-dirty --package sigstat
