name: Statsig FFI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [released, prereleased]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        config:
          - target: amazonlinux2-arm64
            platform: linux/arm64
            runner: statsig-ubuntu-arm64

          - target: amazonlinux2023-arm64
            platform: linux/arm64
            runner: statsig-ubuntu-arm64
            always_build: true
            upload_statsig_ffi_h: true

          - target: amazonlinux2-x86_64
            platform: linux/amd64
            runner: ubuntu-latest

          - target: amazonlinux2023-x86_64
            platform: linux/amd64
            runner: ubuntu-latest

    runs-on: ${{ matrix.config.runner }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Build Statsig FFI
        if: ${{ github.ref_name == 'main' || matrix.config.always_build || github.event_name == 'release' }}
        uses: ./.github/actions/build-ffi-linux
        with:
          target: ${{ matrix.config.target }}
          platform: ${{ matrix.config.platform }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          app_private_key: ${{ secrets.KONG_APP_KEY_V2 }}
          build_for_release: ${{ matrix.config.always_build || github.event_name == 'release' }}


      - name: Make Target Directory Accessible
        if: ${{ github.event_name == 'release' }}
        run: sudo chown -R $(whoami) target/

      - name: Upload Release Asset to Server Core
        if: ${{ github.event_name == 'release' }}
        uses: ./.github/actions/upload-release-asset
        with:
          repositories: ${{ github.event.repository.name }}
          asset_name: statsig-ffi-${{ matrix.config.target }}
          app_private_key: ${{ secrets.KONG_APP_KEY_V2 }}
          pattern: target/**/${{ matrix.config.target }}/**/{release,debug}/libstatsig_ffi.so

      - name: Upload Release Asset to PHP
        if: ${{ github.event_name == 'release' }}
        uses: ./.github/actions/upload-release-asset
        with:
          repositories: statsig-core-php
          asset_name: statsig-ffi-${{ matrix.config.target }}
          app_private_key: ${{ secrets.KONG_APP_KEY_V2 }}
          pattern: target/**/${{ matrix.config.target }}/**/release/libstatsig_ffi.so

      - name: Upload statsig_ffi.h to PHP
        if: ${{ github.event_name == 'release' && matrix.config.upload_statsig_ffi_h }}
        env:
          GH_APP_ID: '229901'
          GH_APP_INSTALLATION_ID: '36921303'
          GH_APP_PRIVATE_KEY: ${{ secrets.KONG_APP_KEY_V2 }}
        run: ./run gh-attach-asset statsig-ffi/include/statsig_ffi.h --repo statsig-core-php

  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          # Windows builds
          - target: x86_64-pc-windows-msvc
            os: windows-latest

          - target: i686-pc-windows-msvc
            os: windows-latest

          - target: aarch64-pc-windows-msvc
            os: windows-latest
            always_build: true
          
          # macOS builds
          - target: x86_64-apple-darwin
            os: macos-latest

          - target: aarch64-apple-darwin
            os: macos-latest
            always_build: true

    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Build Statsig FFI
        if: ${{ github.ref_name == 'main' || matrix.config.always_build || github.event_name == 'release' }}
        uses: ./.github/actions/build-ffi-mac-and-windows
        with:
          target: ${{ matrix.config.target }}
          app_private_key: ${{ secrets.KONG_APP_KEY_V2 }}
          build_for_release: ${{ matrix.config.always_build || github.event_name == 'release' }}

      - name: Upload Release Asset to Server Core
        if: ${{ github.event_name == 'release' }}
        uses: ./.github/actions/upload-release-asset
        with:
          asset_name: statsig-ffi-${{ matrix.config.target }}
          app_private_key: ${{ secrets.KONG_APP_KEY_V2 }}
          pattern: target/**/${{ matrix.config.target }}/{release,debug}/{statsig_ffi,libstatsig_ffi}.{dll,pdb,dylib}
          repositories: ${{ github.event.repository.name }}

      - name: Upload Release Asset to PHP
        if: ${{ github.event_name == 'release' }}
        uses: ./.github/actions/upload-release-asset
        with:
          asset_name: statsig-ffi-${{ matrix.config.target }}
          app_private_key: ${{ secrets.KONG_APP_KEY_V2 }}
          pattern: target/**/${{ matrix.config.target }}/release/{statsig_ffi,libstatsig_ffi}.{dll,pdb,dylib}
          repositories: statsig-core-php
