name: Publish Statsig Java SDK

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'The StatsigFFI workflow run that built the artifacts to publish'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get Workflow Run Info
      id: workflow_info
      uses: actions/github-script@v6
      with:
        script: |
          const run = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.event.inputs.workflow_run_id }}
          });
          console.log(`Workflow Run Name: ${run.data.name}`);
          console.log(`Workflow Run Status: ${run.data.status}`);
          console.log(`Workflow Run Conclusion: ${run.data.conclusion}`);
          if (run.data.status === 'completed' && run.data.conclusion === 'success') {
            return true;
          }
          return false;

    - name: Download Artifacts
      if: steps.workflow_info.outputs.result == 'true'
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: statsig-ffi.yml
        run_id: ${{ github.event.inputs.workflow_run_id }}
        if_no_artifact_found: fail
        path: artifacts

    - name: List Artifacts
      if: steps.workflow_info.outputs.result == 'true'
      run: |
        echo "Listing downloaded artifacts:"
        for artifact in artifacts/*; do
          if [ -d "$artifact" ]; then
            echo "Artifact: $(basename "$artifact")"
            du -sh "$artifact"
          fi
        done
