name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}

jobs:
  run-bindings-tests:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        lang:
          - python
          - node
          - java
          - rust
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - uses: Swatinem/rust-cache@v2

      - name: Install NPM Dependencies
        run: |
          pnpm install --dir cli
          pip3 install pytest maturin patchelf pytest_httpserver

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          ./tore unit-tests ${{ matrix.lang }} \
            --no-docker

