name: Statsig Rust Publish

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'The StatsigFFI workflow run that built the artifacts to publish'
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Get Workflow Run Info
        id: workflow_run_info
        uses: ./.github/actions/verify-workflow-run-successful

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.workflow_run_info.outputs.commit_sha }}

      - name: Cache Cargo Build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Apply Beta Tag
        run: cargo exec beta-tag-package

      - name: Check Package
        working-directory: ./statsig-lib
        run: cargo package --allow-dirty

      - name: Publish to crates.io
        working-directory: ./statsig-lib
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --allow-dirty