name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}

jobs:
  run-lang-specific-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build Docker Image
        id: build-docker-image
        uses: ./.github/actions/build-docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile_path: cli/src/docker/Dockerfile.debian
          docker_image_tag: statsig/server-core-test-runner
          gh_token: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}

      - name: Install NPM Dependencies
        run: cd cli && pnpm install

      - name: Run Tests
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"' # prevents "the input device is not a TTY" error
        run: |
          ./run unit-tests --skip-docker-build

  run-rust-tests:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - run: cargo test -p sigstat

      - run: cargo test -p sigstat --features with_zstd

