name: Statsig Java

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}
  FORCE_COLOR: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
        cache-dependency-path: |
          statsig-ffi/bindings/java/*.gradle*
          statsig-ffi/bindings/java/**/gradle-wrapper.properties

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2

    - name: Build Statsig FFI
      run: cargo build -p statsig_ffi

    - name: Copy FFI to Java
      run: |
        mkdir -p statsig-ffi/bindings/java/src/main/resources/native
        cp target/debug/libstatsig_ffi.so statsig-ffi/bindings/java/src/main/resources/native

    - name: Run Java Tests
      working-directory: ./statsig-ffi/bindings/java
      run: ./gradlew test --rerun-tasks --console rich


