name: Statsig PHP Publish

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'The StatsigFFI workflow run that built the artifacts to publish'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Run Info
        id: workflow_run_info
        uses: ./.github/actions/verify-workflow-run-successful

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.KONG_APP_ID }}
          private-key: ${{ secrets.SERVER_CORE_KONG_APP_PRIVATE_KEY }}
          owner: statsig-io

      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: statsig-ffi.yml
          run_id: ${{ github.event.inputs.workflow_run_id }}
          if_no_artifact_found: fail
          path: artifacts

      - name: List Artifacts
        run: |
          echo "Listing downloaded artifacts:"
          for artifact in artifacts/*; do
            if [ -d "$artifact" ]; then
              echo "Artifact: $(basename "$artifact")"
              du -sh "$artifact"
            fi
          done

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.workflow_run_info.outputs.commit_sha }}

      - name: Push to Packagist Repository
        run: |
          cd statsig-php
          git init
          git config user.name "statsig-kong[bot]"
          git config user.email "statsig-kong[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update statsig-php (commit: ${{ github.sha }})"
          git push https://oauth2:${{ steps.app-token.outputs.token }}@github.com/statsig-io/sigstat-php.git HEAD:main --force


 