name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}

jobs:
  run-lang-specific-tests:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian
          # - alpine
        arch:
          - [x86_64, amd64, ubuntu-latest]
          - [aarch64, arm64, statsig-ubuntu-arm64]

    runs-on: ${{ matrix.arch[2] }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build Docker Image
        id: build-docker-image
        uses: ./.github/actions/build-docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          gh_token: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
          dockerfile_path: cli/src/docker/Dockerfile.${{ matrix.os }}
          docker_image_tag: statsig/server-core-${{ matrix.os }}-${{ matrix.arch[0] }}
          platform: linux/${{ matrix.arch[1] }}

      - name: Install NPM Dependencies
        run: cd cli && pnpm install

      - name: Run Tests
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"' # prevents "the input device is not a TTY" error
        run: |
          ./run unit-tests --skip-docker-build --os ${{ matrix.os }} --arch ${{ matrix.arch[0] }}

  run-rust-tests:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - run: cargo test -p sigstat

      - run: cargo test -p sigstat --features with_zstd

