name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker Image
        uses: ./.github/actions/build-docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          gh_token: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
          dockerfile_path: cli/src/docker/Dockerfile.debian
          docker_image_tag: statsig/server-core-debian-x86_64
          platform: linux/amd64

  run-bindings-tests:
    needs: build-docker-image
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        lang:
          - python
          - node
          - java
          - rust
          - php

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Load Docker Image
        uses: ./.github/actions/build-docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          gh_token: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
          dockerfile_path: cli/src/docker/Dockerfile.debian
          docker_image_tag: statsig/server-core-debian-x86_64
          platform: linux/amd64

      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - uses: Swatinem/rust-cache@v2

      - name: Install NPM Dependencies
        run: pnpm install --dir cli

      - name: Run Tests
        run: ./tore test ${{ matrix.lang }} --arch x86_64 --os debian --skip-docker-build
