# This file generated and copied from statsig-pyo3
# To update, see statsig-pyo3/.github/workflows/CI.yml

name: Statsig Python

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-13
            target: x86_64
          - runner: macos-14
            target: aarch64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: statsig-pyo3
          target: ${{ matrix.platform.target }}
          args: --release --out dist
          sccache: 'true'

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: statsig-pyo3/dist

      - name: Test
        run: |
          cd statsig-pyo3
          pip install pytest cachetools pytest_httpserver
          pip install sigstat_python_core --no-index --find-links dist --force-reinstall -v
          python3 -m pytest tests --capture=no -v

