name: Statsig Python

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: true
  POETRY_PYPI_TOKEN_PYPI_TEST: ${{ secrets.SIGTAT_PYPI_TEST_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./statsig-ffi/bindings/python
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --with=dev

      - name: Run Tests
        run: poetry run pytest

      - name: Increment Version
        if: ${{ github.event_name == 'pull_request' }}
        run: poetry version prerelease

      - name: Build Package
        run: poetry build

      - name: Publish to TestPyPI
        if: ${{ github.ref_name == 'main' }}
        run: poetry publish --repository pypi-test
          
