name: Statsig Java Publish

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'The StatsigFFI workflow run that built the artifacts to publish'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get Workflow Run Info
      uses: actions/github-script@v7
      with:
        script: |
          const run = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.event.inputs.workflow_run_id }}
          });

          console.log(`Workflow Run Name: ${run.data.name}`);
          console.log(`Workflow Run Status: ${run.data.status}`);
          console.log(`Workflow Run Conclusion: ${run.data.conclusion}`);

          if (run.data.status !== 'completed' || run.data.conclusion !== 'success') {
            console.error(`StatsigFFI run must be completed and successful before publishing Java SDK`);
            process.exit(1);
          }

    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: statsig-ffi.yml
        run_id: ${{ github.event.inputs.workflow_run_id }}
        if_no_artifact_found: fail
        path: artifacts

    - name: List Artifacts
      run: |
        echo "Listing downloaded artifacts:"
        for artifact in artifacts/*; do
          if [ -d "$artifact" ]; then
            echo "Artifact: $(basename "$artifact")"
            du -sh "$artifact"
          fi
        done