name: Statsig FFI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        config:
          - target: amazonlinux2-arm64
            platform: linux/arm64
            runner: statsig-ubuntu-arm64

          - target: amazonlinux2023-arm64
            platform: linux/arm64
            runner: statsig-ubuntu-arm64

          - target: amazonlinux2-x86_64
            platform: linux/amd64
            runner: ubuntu-latest

          - target: amazonlinux2023-x86_64
            platform: linux/amd64
            runner: ubuntu-latest
            always_build: true

    runs-on: ${{ matrix.config.runner }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Build Statsig FFI
        if: ${{ github.ref_name == 'main' || matrix.config.always_build }}
        uses: ./.github/actions/build-ffi-linux
        with:
          target: ${{ matrix.config.target }}
          platform: ${{ matrix.config.platform }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-mac-and-windows:
    strategy:
      fail-fast: false
      matrix:
        config:
          # Windows builds
          - target: x86_64-pc-windows-msvc
            os: windows-latest

          - target: i686-pc-windows-msvc
            os: windows-latest

          - target: aarch64-pc-windows-msvc
            os: windows-latest
            always_build: true
          
          # macOS builds
          - target: x86_64-apple-darwin
            os: macos-latest

          - target: aarch64-apple-darwin
            os: macos-latest
            always_build: true

    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Build Statsig FFI
        if: ${{ github.ref_name == 'main' || matrix.config.always_build }}
        uses: ./.github/actions/build-ffi-mac-and-windows
        with:
          target: ${{ matrix.config.target }}

  trigger-publish-actions:
    if: ${{ github.ref_name == 'main' }}
    needs: [build-linux, build-mac-and-windows] # depend on all builds
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Publish Actions
        if: github.event.repository.private
        uses: actions/github-script@v6
        with:
          script: |
            const args = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              inputs: {
                workflow_run_id: '${{ github.run_id }}'
              }
            }

            github.rest.actions.createWorkflowDispatch({
              ...args,
              workflow_id: 'statsig-java-publish.yml'
            })

            github.rest.actions.createWorkflowDispatch({
              ...args,
              workflow_id: 'statsig-php-publish.yml'
            })

            github.rest.actions.createWorkflowDispatch({
              ...args,
              workflow_id: 'statsig-rust-publish.yml'
            })