name: Statsig Rust Publish

on:
  workflow_dispatch:
  release:
    types: [released, prereleased]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Publish Statsig Grpc
        run: |
          cargo package --allow-dirty --package sigstat-grpc
          cargo publish --allow-dirty --package sigstat-grpc

      - name: Publish Statsig Lib
        run: |
          cargo package --allow-dirty --package statsig-rust
          cargo publish --allow-dirty --package statsig-rust
