name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}

jobs:
  run-bindings-tests:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        lang:
          - python
          - node
          - java
          - rust
          - php

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - uses: Swatinem/rust-cache@v2

      - name: Install NPM Dependencies
        run: pnpm install --dir cli

      - name: '[Python] Install Dependencies'
        if: matrix.lang == 'python'
        run: pip3 install pytest maturin patchelf pytest_httpserver

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: '[Rust] Install cargo-nextest'
        if: matrix.lang == 'rust'
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Run Tests
        run: ./tore test ${{ matrix.lang }} --no-docker --arch x86_64 --os debian
