name: Windows Package Verification

on:
  push:

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true
  STATSIG_SERVER_SDK_KEY: ${{ secrets.KONG_SERVER_SDK_KEY }}

jobs:
  node-package-verification:
    timeout-minutes: 10
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Install Node Dependencies
        working-directory: examples/node/verify-package
        run: |
          pnpm init
          pnpm install @statsig/statsig-node-core@beta typescript tsx @types/node
          pnpm exec tsx verify.ts
